services:
    currency-exchange:
        image: budcoded/currency-exchange-service:latest
        mem_limit: 700m
        ports:
            - 8000:8000
        networks:
            - currency_network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

    currency-conversion:
        image: budcoded/currency-conversion-service:latest
        mem_limit: 700m
        ports:
            - 8100:8100
        networks:
            - currency_network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

    api-gateway:
        image: budcoded/api-gateway:latest
        mem_limit: 700m
        ports:
            - 8765:8765
        networks:
            - currency_network
        depends_on:
            - naming-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

    naming-server:
        image: budcoded/naming-server:latest
        mem_limit: 700m
        ports:
            - 8761:8761
        networks:
            - currency_network

    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 700m
        ports:
            - 9411:9411
        networks:
            - currency_network

networks:
    currency_network: