apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-01-20T06:48:09Z"
    generation: 1
    labels:
        app: currency-exchange
    name: currency-exchange
    namespace: default
    resourceVersion: "19144"
    uid: 7c3c3413-8301-4f93-a5ab-034d66ed8cb2
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: currency-exchange
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: currency-exchange
        spec:
            containers:
                -   image: budcoded/currency-exchange-service-k8s:latest
                    imagePullPolicy: Always
                    name: currency-exchange-service-k8s
                    resources: { }
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: { }
            terminationGracePeriodSeconds: 30
status:
    availableReplicas: 1
    conditions:
        -   lastTransitionTime: "2024-01-20T06:48:45Z"
            lastUpdateTime: "2024-01-20T06:48:45Z"
            message: Deployment has minimum availability.
            reason: MinimumReplicasAvailable
            status: "True"
            type: Available
        -   lastTransitionTime: "2024-01-20T06:48:09Z"
            lastUpdateTime: "2024-01-20T06:48:45Z"
            message: ReplicaSet "currency-exchange-5557b5c4d6" has successfully progressed.
            reason: NewReplicaSetAvailable
            status: "True"
            type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1

---

apiVersion: v1
kind: Service
metadata:
    creationTimestamp: "2024-01-20T06:49:34Z"
    labels:
        app: currency-exchange
    name: currency-exchange
    namespace: default
    resourceVersion: "19189"
    uid: 32463d5c-d55d-455c-842f-d827d0fb9593
spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.101.248.203
    clusterIPs:
        - 10.101.248.203
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
        - IPv4
    ipFamilyPolicy: SingleStack
    ports:
        - nodePort: 32206
          port: 8000
          protocol: TCP
          targetPort: 8000
    selector:
        app: currency-exchange
    sessionAffinity: None
    type: LoadBalancer
status:
    loadBalancer: {}
